org: mattkruse
app: battlescripts-test
service: battlescripts-test

custom:
  playerTableName: battlescripts-player
  gameTableName: battlescripts-game
  userTableName: battlescripts-user
  rendererTableName: battlescripts-renderer

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  memorySize: 8000
  region: us-east-1
  timeout: 30
  environment:
    playerTableName: ${self:custom.playerTableName}
    gameTableName: ${self:custom.gameTableName}
    userTableName: ${self:custom.userTableName}
    rendererTableName: ${self:custom.rendererTableName}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: '*'

functions:
  match:
    handler: functions/handler.match
    events:
      - http:
          path: /match
          method: post
          cors: true

  # Player API's
  # ------------
  getPlayer:
    handler: functions/player.get
    events:
      - http:
          path: /player/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
  createPlayer:
    handler: functions/player.create
    events:
      - http:
          path: /player/
          method: post
          cors: true
  updatePlayer:
    handler: functions/player.update
    events:
      - http:
          path: /player/{id}
          method: put
          cors: true
          request:
            parameters:
              paths:
                id: true
  deletePlayer:
    handler: functions/player.delete
    events:
      - http:
          path: /player/{id}
          method: delete
          cors: true
          request:
            parameters:
              paths:
                id: true

  # Game API's
  # ------------
  getGame:
    handler: functions/game.get
    events:
      - http:
          path: /game/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
  createGame:
    handler: functions/game.create
    events:
      - http:
          path: /game/
          method: post
          cors: true
  updateGame:
    handler: functions/game.update
    events:
      - http:
          path: /game/{id}
          method: put
          cors: true
          request:
            parameters:
              paths:
                id: true
  deleteGame:
    handler: functions/game.delete
    events:
      - http:
          path: /game/{id}
          method: delete
          cors: true
          request:
            parameters:
              paths:
                id: true

  # Renderer API's
  # --------------
  getRenderer:
    handler: functions/renderer.get
    events:
      - http:
          path: /renderer/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
  createRenderer:
    handler: functions/renderer.create
    events:
      - http:
          path: /renderer/
          method: post
          cors: true
  updateRenderer:
    handler: functions/renderer.update
    events:
      - http:
          path: /renderer/{id}
          method: put
          cors: true
          request:
            parameters:
              paths:
                id: true
  deleteRenderer:
    handler: functions/renderer.delete
    events:
      - http:
          path: /renderer/{id}
          method: delete
          cors: true
          request:
            parameters:
              paths:
                id: true

resources: # CloudFormation template syntax
  Resources:
    GameTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.gameTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    PlayerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.playerTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.userTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    RendeerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.rendererTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
